version: "3.8"

services:
  i2pd_yggdrasil:
    image: i2pd_yggdrasil:${APP_VERSION:-latest}
    container_name: i2pd_yggdrasil
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      # I2P Service Ports
      - "2827:2827"   # BOB Bridge
      - "4444:4444"   # HTTP Proxy
      - "4447:4447"   # SOCKS Proxy
      - "7070:7070"   # Web Console
      - "7650:7650"   # I2PControl
      - "7654:7654"   # I2CP
      - "7656:7656"   # SAM Bridge
      - "10765:10765" # Main I2P Listener
      # Yggdrasil Ports
      - "10654:10654" # Yggdrasil Listener
    environment:
      - TZ=UTC
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bash", "-c", "pgrep i2pd && pgrep yggdrasil"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

